// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as TemporalPprRetrieveProcedure from "../temporal_ppr_retrieve_procedure";

export type TemporalPprRetrieveArgs = __Infer<typeof TemporalPprRetrieveProcedure.params>;
export type TemporalPprRetrieveResult = __Infer<typeof TemporalPprRetrieveProcedure.returnType>;

