// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import IngestTemporalClaimReducer from "../ingest_temporal_claim_reducer";
import IngestTemporalEdgeReducer from "../ingest_temporal_edge_reducer";
import RunMaintenanceReducer from "../run_maintenance_reducer";
import RunMaintenanceNowReducer from "../run_maintenance_now_reducer";
import SeedMaintenanceJobsReducer from "../seed_maintenance_jobs_reducer";
import UpsertNodeReducer from "../upsert_node_reducer";

export type IngestTemporalClaimParams = __Infer<typeof IngestTemporalClaimReducer>;
export type IngestTemporalEdgeParams = __Infer<typeof IngestTemporalEdgeReducer>;
export type RunMaintenanceParams = __Infer<typeof RunMaintenanceReducer>;
export type RunMaintenanceNowParams = __Infer<typeof RunMaintenanceNowReducer>;
export type SeedMaintenanceJobsParams = __Infer<typeof SeedMaintenanceJobsReducer>;
export type UpsertNodeParams = __Infer<typeof UpsertNodeReducer>;

