// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  archiveId: __t.u128().primaryKey().name("archive_id"),
  projectId: __t.string().name("project_id"),
  edgeId: __t.u128().name("edge_id"),
  archivedAtUs: __t.i64().name("archived_at_us"),
  reason: __t.string(),
  snapshotJson: __t.string().name("snapshot_json"),
});
