// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  edgeId: __t.u128().primaryKey().name("edge_id"),
  familyId: __t.u128().name("family_id"),
  projectId: __t.string().name("project_id"),
  subjId: __t.u128().name("subj_id"),
  pred: __t.string(),
  objId: __t.u128().name("obj_id"),
  validFromUs: __t.i64().name("valid_from_us"),
  validToUs: __t.option(__t.i64()).name("valid_to_us"),
  createdAtUs: __t.i64().name("created_at_us"),
  updatedAtUs: __t.i64().name("updated_at_us"),
  confidence: __t.f32(),
  supportCount: __t.u32().name("support_count"),
  contradictionCount: __t.u32().name("contradiction_count"),
  relevance: __t.f32(),
  lastReinforcedAtUs: __t.i64().name("last_reinforced_at_us"),
});
