// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  evidenceId: __t.u128().primaryKey().name("evidence_id"),
  projectId: __t.string().name("project_id"),
  sourceKind: __t.string().name("source_kind"),
  sourceId: __t.string().name("source_id"),
  sourceUri: __t.option(__t.string()).name("source_uri"),
  capturedAtUs: __t.i64().name("captured_at_us"),
  rawExcerpt: __t.option(__t.string()).name("raw_excerpt"),
  hash: __t.string(),
});
