// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  EvidenceInput,
} from "./types";

export default {
  projectId: __t.string(),
  subjectKind: __t.string(),
  subjectName: __t.string(),
  predicate: __t.string(),
  objectKind: __t.string(),
  objectName: __t.string(),
  validFromUs: __t.i64(),
  validToUs: __t.option(__t.i64()),
  confidence: __t.f32(),
  get evidence() {
    return EvidenceInput;
  },
  nowUs: __t.i64(),
};
