// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nodeId: __t.u128().primaryKey().name("node_id"),
  projectId: __t.string().name("project_id"),
  kind: __t.string(),
  name: __t.string(),
  nameNorm: __t.string().name("name_norm"),
  createdAtUs: __t.i64().name("created_at_us"),
  updatedAtUs: __t.i64().name("updated_at_us"),
});
