// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  RetrievalResult,
} from "./types";

export const params = {
  projectId: __t.string(),
  seedNodeIds: __t.array(__t.u128()),
  asOfUs: __t.i64(),
  maxEdges: __t.u32(),
  maxHops: __t.u32(),
  alpha: __t.f32(),
  halfLifeHours: __t.f32(),
  minRelevance: __t.f32(),
};
export const returnType = __t.array(RetrievalResult)