// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Edge = __t.object("Edge", {
  edgeId: __t.u128(),
  familyId: __t.u128(),
  projectId: __t.string(),
  subjId: __t.u128(),
  pred: __t.string(),
  objId: __t.u128(),
  validFromUs: __t.i64(),
  validToUs: __t.option(__t.i64()),
  createdAtUs: __t.i64(),
  updatedAtUs: __t.i64(),
  confidence: __t.f32(),
  supportCount: __t.u32(),
  contradictionCount: __t.u32(),
  relevance: __t.f32(),
  lastReinforcedAtUs: __t.i64(),
});
export type Edge = __Infer<typeof Edge>;

export const EdgeArchive = __t.object("EdgeArchive", {
  archiveId: __t.u128(),
  projectId: __t.string(),
  edgeId: __t.u128(),
  archivedAtUs: __t.i64(),
  reason: __t.string(),
  snapshotJson: __t.string(),
});
export type EdgeArchive = __Infer<typeof EdgeArchive>;

export const EdgeEvidence = __t.object("EdgeEvidence", {
  linkId: __t.u128(),
  edgeId: __t.u128(),
  evidenceId: __t.u128(),
  linkedAtUs: __t.i64(),
});
export type EdgeEvidence = __Infer<typeof EdgeEvidence>;

export const EdgeStats = __t.object("EdgeStats", {
  statsId: __t.u128(),
  projectId: __t.string(),
  subjId: __t.u128(),
  pred: __t.string(),
  objId: __t.u128(),
  n: __t.u32(),
  meanTUs: __t.f64(),
  m2TUs: __t.f64(),
  segmentCount: __t.u32(),
  lastSegmentStartUs: __t.i64(),
  latestObservationUs: __t.i64(),
});
export type EdgeStats = __Infer<typeof EdgeStats>;

export const Evidence = __t.object("Evidence", {
  evidenceId: __t.u128(),
  projectId: __t.string(),
  sourceKind: __t.string(),
  sourceId: __t.string(),
  sourceUri: __t.option(__t.string()),
  capturedAtUs: __t.i64(),
  rawExcerpt: __t.option(__t.string()),
  hash: __t.string(),
});
export type Evidence = __Infer<typeof Evidence>;

export const EvidenceInput = __t.object("EvidenceInput", {
  sourceKind: __t.string(),
  sourceId: __t.string(),
  sourceUri: __t.option(__t.string()),
  capturedAtUs: __t.i64(),
  rawExcerpt: __t.option(__t.string()),
  hash: __t.string(),
});
export type EvidenceInput = __Infer<typeof EvidenceInput>;

export const MaintenanceJob = __t.object("MaintenanceJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  projectId: __t.option(__t.string()),
  jobKind: __t.string(),
  intervalMicros: __t.i64(),
  metadataJson: __t.option(__t.string()),
});
export type MaintenanceJob = __Infer<typeof MaintenanceJob>;

export const ModuleHealth = __t.object("ModuleHealth", {});
export type ModuleHealth = __Infer<typeof ModuleHealth>;

export const ModuleHealthRow = __t.object("ModuleHealthRow", {
  generatedAtUs: __t.i64(),
  nodeCount: __t.u64(),
  edgeCount: __t.u64(),
  evidenceCount: __t.u64(),
  archiveCount: __t.u64(),
  maintenanceJobCount: __t.u64(),
});
export type ModuleHealthRow = __Infer<typeof ModuleHealthRow>;

export const Node = __t.object("Node", {
  nodeId: __t.u128(),
  projectId: __t.string(),
  kind: __t.string(),
  name: __t.string(),
  nameNorm: __t.string(),
  createdAtUs: __t.i64(),
  updatedAtUs: __t.i64(),
});
export type Node = __Infer<typeof Node>;

export const RetrievalResult = __t.object("RetrievalResult", {
  edgeId: __t.u128(),
  subjId: __t.u128(),
  pred: __t.string(),
  objId: __t.u128(),
  validFromUs: __t.i64(),
  validToUs: __t.option(__t.i64()),
  relevance: __t.f32(),
  confidence: __t.f32(),
  supportCount: __t.u32(),
  contradictionCount: __t.u32(),
  evidenceIds: __t.array(__t.u128()),
});
export type RetrievalResult = __Infer<typeof RetrievalResult>;

